feat: 성적 산출 퍼블리싱
EntryDSM/Entry-LTS pull request #15
Opened 2023-02-20 17:13 UTC by jikwan0327

close #5

2023-02-21 10:37 UTC, paperdeer requested changes

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/AllSelect.tsx
> +  const arr = ['A', 'B', 'C', 'D', 'E'];
```suggestion
  const arr:Grade[] = ['A', 'B', 'C', 'D', 'E'];
```
로 바꿔고 컴포넌트 상단으로 빼내주세요.
상수라서 빼놓는게 좋을거 같아요

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/AllSelect.tsx
> +    setElement(copiedItems);
```suggestion
    setElement(element[current].map((res) => (res.grade = grade)));
```
는 어떤가요?

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/AllSelect.tsx
> +      {arr.map((arr: Grade) => {
위에서 타입 지정해주면 맵 함수 돌리면서 타입지정할 필요는 없을 것 같아요

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/AllSelect.tsx
> +        let isClick = arr === grade;
상수인거 같은데 `const`로 바꿔주세요!

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/ProgressBar.tsx
> +const _Circle = styled.div<{ now?: boolean }>`
`now`보다는 `isNow`가 더 boolean값 같아요!

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/ProgressBar.tsx
> +  height: 1.3rem;
혹시 `rem`을 사용한 이유가 있을까요?

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/ProgressBar.tsx
> +  width: 26%;
혹시 %를 사용한 이유가 있을까요?

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/ProgressBar.tsx
> +  ];
컴포넌트 상단으로 뺴내는게 좋아보여요!
그리고 혹시 객체로 감싼 이유가 있을까요?

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/SelectGrade.tsx
> +  let arr = ['A', 'B', 'C', 'D', 'E', 'X'];
이것도 그렇고, `Grade`타입도 그렇고, 공통으로 사용되는 것 같은데
공통으로 사용하는 상수, 타입을 파일로 빼내서 관리하면 좋을 것 같아요

2023-02-21 10:37 UTC, paperdeer commented on src/components/grade/SelectGrade.tsx
> +      <div style={{ display: 'flex', alignItems: 'center' }}>
inline 스타일을 사용한 이유가 있을까요?

2023-02-21 10:37 UTC, paperdeer commented on src/pages/GradePage.tsx
> +  ];
이것도 컴포넌트 상단으로 빼내거나 constant 파일로 뺴내는게 좋아보입니다!

2023-02-21 10:37 UTC, paperdeer commented on src/pages/GradePage.tsx
> +        <_Line></_Line>
```suggestion
        <_Line />
```
로 self closing 하는건 어떤가요

2023-02-21 10:37 UTC, paperdeer commented on src/pages/GradeProgramPage.tsx
> +  grade?: 'A' | 'B' | 'C' | 'D' | 'E' | 'X';
정의되어있는 `Grade` 타입을 사용해 주세요!

2023-02-21 10:37 UTC, paperdeer commented on src/router.tsx
> +          <Route path="/gradeprogram" element={<GradeProgramPage />} />
`path`를 단어별로 구분하면 좋겠어요!
`camelCase` 던지 `kebab-case`로!

2023-02-23 12:36 UTC, paperdeer approved these changes

2023-02-23 12:46 UTC, kimjh11130 approved these changes

2023-02-23 12:46 UTC, merged