feat: 헤더 반응형
EntryDSM/Entry-LTS pull request #21
Opened 2023-03-18 12:54 UTC by jikwan0327

close #19

2023-03-18 14:02 UTC, kimulchan requested changes
리뷰 달아놓았으니 수정하고 다시 페메 남겨주시면 확인하겠습니다@@

2023-03-18 14:02 UTC, kimulchan commented on src/components/Header/index.tsx
> +                      : list.type === 'total' || list.type === 'logout',
total 이면 filter method 아예 안돌리는 로직이 맞을 것 같습니다.

2023-03-18 14:02 UTC, kimulchan commented on src/components/Header/index.tsx
> +                        </_._MenuElement>
key 값 넣어주세요 :)

2023-03-18 14:02 UTC, kimulchan commented on src/components/Header/index.tsx
> +          {localStorage.getItem('access_token') ? (
access token을 여기서만 받아오는게 아닌거 같은데 위로 빼서 같이 관리하는게 좋아보여요! 그리고 변수명도 isLogin 이렇게 지어주면 훨신 더 보기 좋을 것 같습니다!!

2023-03-18 14:02 UTC, kimulchan commented on src/components/Header/style.ts
> +  background-color: white;
menu height 반응형은 조금 않좋은 선택인 것 같습니다... 그냥 px 로 고정하는게 좋아보여요

2023-03-18 14:02 UTC, kimulchan commented on src/components/Header/style.ts
> +  background-color: white;
않 x 안 
오타에요..ㅎㅎ

2023-03-20 02:08 UTC, kimulchan approved these changes

2023-03-20 05:58 UTC, kimjh11130 approved these changes

2023-03-20 07:00 UTC, merged