feat: 메인페이지 height px변경 및 버튼 link 추가
EntryDSM/Entry-LTS pull request #24
Opened 2023-03-22 11:24 UTC by kimjh11130

메인페이지 height 961px로 고정,
button, boarder쪽 link추가
원서 접수, 입학설명회는 추가안함

2023-03-22 13:25 UTC, kimulchan requested changes
수정하세요!!

2023-03-22 13:25 UTC, kimulchan commented on src/components/Main/BoardAtMain.tsx
> +
constant 폴더를 만들어서 넣는게 좋을 것 같습니다.

2023-03-22 13:25 UTC, kimulchan commented on src/components/Main/MainFuction.tsx
> +      onClick: () => scrollTo(0, 1922),
여기도 마찬가지요

2023-03-22 13:25 UTC, kimulchan commented on src/components/Main/BoardAtMain.tsx
> +                {item.length > 25 ? `${item.slice(0, 24)}...` : item}
css ellipsis를 찾아보면 좋을 것 같네요

2023-03-22 13:25 UTC, kimulchan commented on src/components/Main/MainFuction.tsx
> +      onClick: () => scrollTo(0, 1922),
scrollTo 를 저렇게 주는것보다 id를 줘서 a tag로 이동하거나, ref를 주고 scrollIntoView로 이동하는게 좋을 것 같습니다.

2023-03-23 03:11 UTC, kimulchan requested changes
수정 후 페메 다시 보내요

2023-03-23 03:11 UTC, kimulchan commented on src/components/Main/Progress.tsx
> +        ))}
React.Fragment 테그를 사용해서 key값을 넣어줄 수 있습니다!

2023-03-23 03:11 UTC, kimulchan commented on src/components/Main/Progress.tsx
> +  ];
이것도 constant에 넣어주면 좋을 것 같습니다.

2023-03-23 03:11 UTC, kimulchan commented on src/components/Main/Progress.tsx
> +  ];
아래 progressBar는 그냥 map으로 간단하게 처리할 수 있을 것 같은데 한번 고민해보세요.

2023-03-23 04:13 UTC, jikwan0327 approved these changes

2023-03-24 14:54 UTC, jikwan0327 commented on src/components/Main/MainFuction.tsx
> +          {shortcut.map((item) =>
Link또는 a태그 안쪽이 같은거 같은데 중복되는 부분을 컴포넌트로 따로 빼는건 어떨까요?

2023-04-08 03:56 UTC, jikwan0327 approved these changes

2023-04-08 09:06 UTC, jikwan0327 approved these changes

2023-05-11 12:42 UTC, kimulchan approved these changes

2023-05-11 15:16 UTC, merged